### ISSUE TITLE
The example in the README results in all children being walked.

### ISSUE THREAD

**Issue by threehams** [ctrlplusb/react-tree-walker#11]
The example in the README has a few typos which stop it from working (getData vs. getValue), but I can fix those in a PR. The bigger issue is that running the code results in the output:

```
[1, 2, 4, 5, 3]
```

From experimenting, it seems like this library takes an approach similar to shallow rendering - all React elements present within a component's render method are traversed (even if nested within other components), but any components within that component's render method are not traversed.

This isn't very fun to describe in text, so two examples. In both cases, the walk is told to stop after hitting value="4", just like the current example:

```
const app = (
  <div>
    <h1>Hello World!</h1>
    <Foo value={1} />
    <Foo value={2}>
      <Foo value={4}>
        <Foo value={5} />
      </Foo>
    </Foo>
    <Foo value={3} />
  </div>
);

// result: [1,2,4,5,3]
```

```
const Container = ({ value }) => (
  <Foo value={value}>
    <Foo value={5} />
  </Foo>
);

const app = (
  <div>
    <h1>Hello World!</h1>
    <Foo value={1} />
    <Foo value={2}>
      <Container value={4} />
    </Foo>
    <Foo value={3} />
  </div>
);

// result: [1,2,4,3]
```

Is this accurate? If so, I can modify the example to match this.

**Comment by ctrlplusb** [comment]
Hey @threehams yep you are correct.  It walks in depth first fashion - i.e. resolving all the children for each component before continuing onto the next one.

Hmmm, there must be a bug in my example code then. It should only result in `[1, 2, 4, 3]`.

**Comment by mjadobson** [comment]
To elaborate on this issue, it doesn't occur if you the promises are removed:

```javascript
class Foo extends React.Component {
  getData() {
    return Promise.resolve(this.props.value);
  }
  getDataSync() {
    return this.props.value;
  }
  render() {
    return <div>{this.props.children}</div>;
  }
}

function visitor(element, instance, context) {
  if (instance && typeof instance.getDataSync) {
    let value = instance.getDataSync();
    values.push(value);
    return value === 4 ? false : true;
  }
  return true;
}
// result: [1,2,4,3]

function visitor(element, instance, context) {
  if (instance && typeof instance.getData) {
    return instance.getData().then((value) => {
      values.push(value);
      return value === 4 ? false : true;
    });
  }
  return true;
}
// result: [1,2,4,5,3]
```

**Comment by ctrlplusb** [comment]
This should be fixed with the upcoming release. Thanks for the report!
