### ISSUE TITLE
Error when child is react.portal

### ISSUE THREAD

**Issue by IamFake** [ctrlplusb/react-tree-walker#13]
If component has child which is React.Portal - i've got error
`Objects are not valid as a React child`

to reproduce you may use any of the examples for react-modal (https://reactcommunity.org/react-modal)

**Comment by ctrlplusb** [comment]
Hey @IamFake - thanks for this.  Great pickup.

We'll need to investigate how to extend the code to handle portals.

Open to PRs if you feel like giving it a go. :)

**Comment by l0c0luke** [comment]
for me i started getting this once we moved to react16

**Comment by ctrlplusb** [comment]
Portals are now supported in v4 👍
