### ISSUE TITLE
Errror in Edge: 'Error walking react tree'

### ISSUE THREAD

**Issue by dlebedynskyi** [ctrlplusb/react-tree-walker#15]
Hi, 
after update to latest we started seeing 

![image](https://user-images.githubusercontent.com/1182917/32463276-513bb624-c30a-11e7-9178-61273cbfea65.png)

happens only in Edge. 
I wish I could give more details but it is a pain to get anything from IE. 
Fix would be appreciated though

**Comment by ctrlplusb** [comment]
Apologies for the late reply. Are you still having this issue. If so could you please provide me with the call stack. 👍

**Comment by ctrlplusb** [comment]
@dlebedynskyi I am closing this for now.  Please let me know if it is still an issue for you.

**Comment by dlebedynskyi** [comment]
@ctrlplusb  all good. we resolved it. it was error down the chain in IE, that was swallowed/masked in IE with tree-walker as far as I recall
