### ISSUE TITLE
Promise resolved before the entire tree has been resolved

### ISSUE THREAD

**Issue by SamyPesse** [ctrlplusb/react-tree-walker#16]
### Context

I'm trying to use `react-jobs` and [`react-async-bootstrapper`](https://github.com/ctrlplusb/react-async-bootstrapper)  to replace a custom module ([`aqueduc`](https://github.com/SamyPesse/aqueduc)).

Our application has some conditional rendering according to the data that have been fetched (example for a blog application: the component to fetch and render a comment is used in a component to render a blog post only rendering once the blog post has been fetched).

It looks like this use case is not supported by `react-jobs`.

### Bug

But while I was testing, I've found an issue in `react-tree-walker` itself where the promise is resolved, but the "rendering" continues.

Here is an example file to reproduce the issue: https://gist.github.com/SamyPesse/4950194a9ca47c3d91e1226d93b3e802 (with the console output)

**Comment by ctrlplusb** [comment]
Hi @SamyPesse 

Apologies for the late response.

Hmmm, that definitely should not be the case.  It would essentially void the usefulness of this library.  I will have a look at your gist and see if I can pick up any issues. 👍

**Comment by ctrlplusb** [comment]
This has been fixed. Release pending.  Thanks for the report 👍
