### ISSUE TITLE
Do not catch errors in promises and let user catch them

### ISSUE THREAD

**Issue by mohsen1** [ctrlplusb/react-tree-walker#18]
https://github.com/ctrlplusb/react-tree-walker/blob/master/src/index.js#L101

This is making it impossible to catch errors during bootsrap

**Comment by ctrlplusb** [comment]
I'm happy to move forward with this change. 👍

**Comment by ctrlplusb** [comment]
Done 🎉

Actually exposed some nice issues in the process. Thanks for the report.

**Comment by mohsen1** [comment]
Thanks!
