### ISSUE TITLE
Support Shallow Walk

### ISSUE THREAD

**Issue by amccloud** [ctrlplusb/react-tree-walker#2]
It would be nice if you can optionally walk children only. 

One way to do this is to have visitor function optionally return an array of elements to walk next. If it's type Array I think you can assume it is children and proceed with a breadth-first walk.

Example use case: https://github.com/amccloud/await-component

**Comment by ctrlplusb** [comment]
Is there any chance you could create a more isolated example / test of what you are trying to achieve?
