### ISSUE TITLE
Add a note that this is discouraged 

### ISSUE THREAD

**Issue by gaearon** [ctrlplusb/react-tree-walker#37]
Hi! I help maintain React. 

I realize where the need is coming from, but I would appreciate if the project included a large disclaimer that this approach is discouraged. It is very fragile, already doesn’t match the exact semantics of React, and the gap will only widen in the future. We don’t recommend any libraries that want to work well with React in longer term to depend on this, or to use an approach like this. 

What’s the alternatives? We are currently working on getting Suspense ready for use in open source. That should eventually cover data fetching needs (which is what motivated Apollo to do this). For other needs there may be other appropriate solutions.

Sorry to be a bummer. Thanks!

**Comment by ctrlplusb** [comment]
@gaearon I really appreciate your effort to ensure the health of the React eco-system. 👏

I am more than happy to update the docs to inform user's of the risk involved when using this library, along with a suggestion to keep their eyes on the imminent release of Suspense.

I apologise that hadn't considered doing this earlier - it reflects a bit of irresponsibility on my part.

Can't wait for Suspense. 🙏

**Comment by ctrlplusb** [comment]
Done 👍

**Comment by gaearon** [comment]
>One use case I ran into is communicating leaf node data back up to the parent component (some of this data is static, other parts rely on where the leaf node is nested within the react tree). To me the react-call-return pattern seemed like the closest option that was available to support this kind of need, but that has been removed and never supported createContext if I understand correctly.

Wanna raise an RFC with your ideas? We want to bring back call/return in some form but we need to figure out a compelling API for it.
