### ISSUE TITLE
React.forwardRef is not supported

### ISSUE THREAD

**Issue by bartlangelaan** [ctrlplusb/react-tree-walker#38]
I love that you made the new 16.3 context features work with this module.

The new `React.forwardRef` function however doesn't seem to work yet. I have made a code sample here: https://codesandbox.io/s/n4r8zwxz0l.

When the `SubComponent` in the example is directly rendered it works, but when wrapped with the `React.forwardRef` function it doesn't.

**Comment by ctrlplusb** [comment]
https://github.com/ctrlplusb/react-tree-walker/releases/tag/v4.3.0

🎉

Thanks dude!
