### ISSUE TITLE
BlueBird warning for problematic Promise usage

### ISSUE THREAD

**Issue by swernerx** [ctrlplusb/react-tree-walker#4]
I am currently seeing this issue when replacing the native Promise with Bluebirds debug enhanced Promise:

```
Warning: a promise was created in a handler at react-tree-walker/commonjs/index.js:28:14 but was not returned from it, see http://goo.gl/rRqMUw
```

As I see the method is "inherited" from Sindres utilities.

I would be eager what you think on the issue or whether we want to fix it.

**Comment by ctrlplusb** [comment]
Hmmm, may be interesting to post it on Sindre's respective repo.  I haven't noticed any issues thusfar, so for now we can keep this up as a "known" issue.
