### ISSUE TITLE
Rehydrate server -> client with unique IDs

### ISSUE THREAD

**Issue by tamagokun** [ctrlplusb/react-tree-walker#6]
I've implemented a basic HOC so components can load data on the server, and then rehydrate with that state in the client.

The issue I keep getting hung up on is how to track unique keys/ids for each component. As the walker traverses the tree, it should create a unique id for each component (_exactly once_) and then when the tree is traversed on the client side, it gets the same ids and can grab its props from a global state object.

All of my approaches seem to do alright until I start using the same component with different props, and then they just fall flat because the ids overwrite.

Here's some example code to help illustrate what i'm doing:

```js
// HOC that will resolve a promise and pass the resolved promise
// as props of the wrapped component.

// react-tree-walker's visitor function will return the promise from `fetchProps` during traversal.
export default getProps => ComposedComponent => {
  let id = null

  class Component extends React.Component {
    state = {props: null}

    constructor (props, context) {
      super(props, context)
      const {store} = context

      // browser doesn't get an id since `fetchProps` already ran. Need to get id here.
      if (process.browser) {
        id = store.getNextId()
      }

      if (id) this.state = {props: store.get(id)}
    }

    fetchProps = async () => {
      const {store} = this.context
      const props = await fetch('...')
      if (!id) {
        id = store.getNextId()
      }

      store.register(id, props)
      this.setState({props})
      return true
    }

    render () {
      return <ComposedComponent {...this.state.props} />
    }
  }
}
```

```js
const Component = ({page}) => <li>{page.title}</li>

export default asyncHoc(async ({props}) => {
  const page = fetch(`api/pages/${props.id}`)
  return {page}
})(Component)
```

```js
const App = () => <div><Component id='1' /><Component id='2' /></div>
```

**Comment by ctrlplusb** [comment]
I just had a similar problem on my [`react-jobs`](https://github.com/ctrlplusb/react-jobs) implementation, ids need to be per-element (i.e. component instance).  But then the context needs to reset its ids between runs for them to properly match.

**Comment by tamagokun** [comment]
oh YES. That was exactly what it needed. I just reset the id counter in the `constructor` of the main context provider and BAM, worked perfectly. Brilliant! Thank you

**Comment by ctrlplusb** [comment]
No problem! Let me know your projects details and I would be happy to link you.

**Comment by tamagokun** [comment]
It's a little next.js wrapper for building sites that integrate with Fridge CMS.

https://github.com/fridge-cms/fridge.js
