### ISSUE TITLE
Issue with multiple children

### ISSUE THREAD

**Issue by grxy** [ctrlplusb/react-tree-walker#9]
I ran into the following problem where not all nested children would be visited:

## This works

    const A = ({ children }) => children
    const B = ({ children }) => <div>{children}</div>

    const tree = (
        <A>
            <B />
            <B />
        </A>
    )

    reactTreeWalker(tree, visitor, context)

## So does this

    const A = ({ children }) => <div>{children}</div>
    const B = ({ children }) => children

    const tree = (
        <A>
            <B />
            <B />
        </A>
    )

    reactTreeWalker(tree, visitor, context)

## This does not work

Because there are no basic HTML elements wrapping the children of A, those individual children are not visited

    const A = ({ children }) => children
    const B = ({ children }) => children

    const tree = (
        <A>
            <B />
            <B />
        </A>
    )

    reactTreeWalker(tree, visitor, context)

A PR will follow shortly and should provide a fix for this issue.

**Comment by ctrlplusb** [comment]
Hey @grxy 

Awesome, thanks so much for picking this up.  I'll try review and merge within the next 24 hours. 👍

**Comment by grxy** [comment]
@ctrlplusb No prob, dude. I actually noticed the issue when writing unit tests for my code while using this. 

P.S. Great work breaking it out from react-apollo!

**Comment by ctrlplusb** [comment]
Hi @grxy 👋

Apologies for the late one on this.

I have struggled to recreate your initial issue.  I have added another [branch](https://github.com/ctrlplusb/react-tree-walker/tree/issue9) containing a test that I was initially expecting to fail as it doesn't have your [fix](https://github.com/ctrlplusb/react-tree-walker/pull/10) applied. The test passes though.

Do you mind having a look to see if I have configured the test correctly?

Thanks!

**Comment by grxy** [comment]
@ctrlplusb The issue happens when you have multiple react components that are siblings, so if you updated your tree to be:
```jsx
const tree = (
      <OnlyChildren something={1}>
        <OnlyChildren something={2}>
          <div>Hello world!</div>
        </OnlyChildren>
        <OnlyChildren something={3}>
          <div>Hello world!</div>
        </OnlyChildren>
      </OnlyChildren>
    )
```
you would expect actual to be `[1, 2, 3]`, when in fact the children are never visited, resulting in actual being only `[1]`. See screenshot:

![image](https://user-images.githubusercontent.com/836644/27043859-cc8ffa0e-4f58-11e7-8f3f-601cd304b961.png)

**Comment by ctrlplusb** [comment]
Perfect thanks!

**Comment by grxy** [comment]
@ctrlplusb Any chance you'll be able to merge my PR and publish 2.1.2 soon?

**Comment by ctrlplusb** [comment]
All done and published. Thanks for being persistent with me!

**Comment by grxy** [comment]
@ctrlplusb Great! Thank you!
